#!/bin/bash
REMUSER=cantrel2
LOCUSER=`whoami`
REPONAME=develop

REMOTE="/home/$REMUSER/projects/llvm-project"
LOCAL="/home/$LOCUSER/projects/llvm-project"
INSTANCE=""
GCPIP=""

inst()
{
  echo `gcloud compute instances list | tail -n 1 | awk '{ print $1 }'`
}

up()
{
	[[ $1 ]] && INSTANCE="$1" || INSTANCE=$(inst)
  gcloud compute instances start "$INSTANCE"
}

down()
{
  [[ $1 ]] && INSTANCE="$1" || INSTANCE=$(inst)
  gcloud compute instances stop "$INSTANCE"
}

ip()
{
  LINE=`gcloud compute instances list | tail -n 1`
  EXTIP=`echo $LINE | awk '{ print $9 }'`
  STATUS=`echo $LINE | awk '{ print $10 }'`

  # If STATUS is empty, the external ip column is blank (instance isn't on)
  # so return "", otherwise return the IP address
  [[ -z "$STATUS" ]] && GCPIP="" || GCPIP="$EXTIP"
  echo -n "$GCPIP"
}

sync()
{
  up
  ip >/dev/null
  [[ $1 ]] && REPONAME="$1"

	REMOTEBIN="$REMOTE/$REPONAME/build/bin"
	LOCALBIN="$LOCAL/$REPONAME/build/bin"
	REMOTEINC="$REMOTE/$REPONAME/build/lib/clang/9.0.0/include"
	LOCALINC="$LOCAL/$REPONAME/build/lib/clang/9.0.0"

  mkdir -p "$LOCALBIN"
  mkdir -p "$LOCALINC"

  sleep 4
	rsync -PLc -r --stats "$REMUSER"@"$GCPIP":"$REMOTEBIN"/clang "$LOCALBIN"/clang
	rsync -PLc -r --stats "$REMUSER"@"$GCPIP":"$REMOTEINC" "$LOCALINC"
  down
}

freshen()
{
  up
  ip >/dev/null

	[[ $1 ]] && REPONAME="$1"
	[[ $2 ]] && CORES="$2" || CORES=48

  CMAKEOPTS="-DLLVM_ENABLE_PROJECTS=clang -G \"Unix Makefiles\" ../llvm"

  CMDSTR=""
  CMDSTR="${CMDSTR}cd $REMOTE/$REPONAME/build;"
	CMDSTR="${CMDSTR}pwd;"
  CMDSTR="${CMDSTR}git branch -vv;"
  CMDSTR="${CMDSTR}git pull;"
  CMDSTR="${CMDSTR}rm -rf *;"
  CMDSTR="${CMDSTR}cmake $CMAKEOPTS;"
  CMDSTR="${CMDSTR}make -j $CORES;"
	
  sleep 4
	ssh -o StrictHostKeyChecking=no "$REMUSER"@"$GCPIP" "$CMDSTR"
  down
}

build()
{
  up
  ip >/dev/null

	[[ $1 ]] && REPONAME="$1"
	[[ $2 ]] && CORES="$2" || CORES=48

  CMDSTR=""
  CMDSTR="${CMDSTR}cd $REMOTE/$REPONAME/build;"
	CMDSTR="${CMDSTR}pwd;"
  CMDSTR="${CMDSTR}git branch -vv;"
  CMDSTR="${CMDSTR}git pull;"
  CMDSTR="${CMDSTR}make -j $CORES;"
	
  sleep 3
	ssh -o StrictHostKeyChecking=no "$REMUSER"@"$GCPIP" "$CMDSTR"
  down
}

run()
{
  up
  ip >/dev/null
  sleep 3
  ssh -o StrictHostKeyChecking=no "$REMUSER"@"$GCPIP" "$*"
  down
}

connect()
{
  up
  ip >/dev/null
  #whoami
  #echo "remuser is $REMUSER"
  #echo "ip is $GCPIP"
  sleep 3 # connection fails if we try too soon
  ssh -o StrictHostKeyChecking=no "$REMUSER"@"$GCPIP"
  down
}

main()
{
  action="$1"
  shift
  case "$action" in
  build) # build the repo
    build "$@"
    ;;
  sync) # sync built clang and includes
    sync "$@"
    ;;
  ip) # get ip (if running)
    ip "$@"
    ;;
  up) # bring up instance
    up "$@"
    ;;
  down) # bring down instance
    down "$@"
    ;;
  run) # run a command
    run "$@"
    ;;
  inst) # (first) instance name
    inst "$@"
    ;;
  connect) # connect for interactive session
    connect "$@"
    ;;
  freshen) # clear out build/ and rerun cmake
    freshen "$@"
    ;;
  *)
    echo -en "Usage: gcptool [ACTTION]"
  esac
}

main "$@"
