#!/bin/bash

class()
{
	# $1 is the class number
	# $2 is the week number
	if (( $# != 2 )); then
		echo 'Usage: schooltasks class_number week_number'
		for i in "$@"; do
			echo $i;
		done
		exit
	fi
	
	tickets new "school $1 week $2 reading"
	tickets new "school $1 week $2 lecture"
	tickets new "school $1 week $2 slides"
	tickets new "school $1 week $2 homework"
	tickets new "school $1 week $2 materials"
}

#Fall 2017
#class CS320 "$(date -dnext-monday +'%a %b %e')"
#class CS333 "$(date -dnext-monday +'%a %b %e')"
#class CS486 "$(date -dnext-monday +'%a %b %e')"
#class CS494 "$(date -dnext-monday +'%a %b %e')"

#winter 2018
class CS333 "$(date -dnext-monday +'%a %b %e')"
class CS454 "$(date -dnext-monday +'%a %b %e')"
class CS305 "$(date -dnext-monday +'%a %b %e')"
